# Generated by Django 4.0 on 2022-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Vendor'), (3, 'Customer')], default=3, verbose_name='User Type'),
        ),
    ]
